repos:
  -   repo: https://github.com/Yelp/detect-secrets
      rev: v1.2.0
      hooks:
        -   id: detect-secrets
            args: ['--baseline', '.secrets.baseline']
            exclude: go.sum
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: no-commit-to-branch
            args: [--branch, develop, --branch, master, --branch, main, --pattern, release/.*]
