arborist_endpoint: 'NONE'
global_reader_role: 'dummyGlobalReaderRole'
# see tests/setup_cdm/README.md
atlas_db:
  host: localhost
  port: '5433'
  username: postgres
  password: mysecretpassword # pragma: allowlist secret
  db: postgres
  schema: atlas
# optional validation config:
validate:
  single_observation_for_concept_ids:
    # HARE concept id:
    - '2000007027'
catch_all_cohort_id: 4
worker_pool_size: 5
batch_size: 50
