name: Golang CI Workflow

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      atlas_db:
        image: postgres:9.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword #pragma: allowlist secret
          POSTGRES_DB: postgres
        ports:
        - 5433:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      cdm_and_results_db:
        image: postgres:9.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword #pragma: allowlist secret
          POSTGRES_DB: postgres
        ports:
        - 5434:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      COVERAGE_PROFILE_OUTPUT_LOCATION: "./profile.cov"
    steps:
      - name: Checkout code / lint code / install dependencies for goveralls / run tests
        uses: uc-cdis/.github/.github/actions/golang-ci@master
        with:
          COVERAGE_PROFILE_OUTPUT_LOCATION: ${{ env.COVERAGE_PROFILE_OUTPUT_LOCATION }}
      - name: Send coverage to coveralls using goveralls
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=${{ env.COVERAGE_PROFILE_OUTPUT_LOCATION }} -service=github
