name: Golang tests with coverage

on: push

jobs:
  ci:
    name: Golang tests with coverage
    uses: uc-cdis/.github/.github/workflows/golang-ci-test-coverage.yaml@feat/golang-ci-test-coverage
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
